### ISSUE TITLE
Fix breaking changes in FastBoot 1.0

### ISSUE THREAD

**Issue by simonihmig** [mike-north/ember-phoenix#78]
The current `ember-cli-fastboot` releases (1.0.0-rc.1 and above) introduce breaking changes. These will most likely break your current FastBoot implementation.

See https://github.com/ember-fastboot/ember-cli-fastboot/issues/387 for more information and a guide on how to fix your addon. Also you may want to visit the `-fastboot` Slack channel to get help from other users.

*Note: this issue has been created automatically, by searching for certain patterns in your code. If you think this has been falsely created, feel free to close!*

**Comment by oskarrough** [comment]
Hi, I've been using this addon happily with fastboot for some time but I'm now seeing this error. 

It comes from here https://github.com/mike-north/ember-phoenix/blob/master/vendor/phoenix.js#L1025. Is it an older version of this? https://github.com/phoenixframework/phoenix/blob/master/assets/js/phoenix.js — not sure if this can be fixed by updating this vendor import.

```
'ReferenceError: ActiveXObject is not defined\n    at Function.request (/Users/oskar/Sites/xxx/player/tmp/broccoli_merge_trees-output_path-LSftJmM8.tmp/assets/vendor/phoenix.js:1025:1)\n    at LongPoll.poll (/Users/oskar/Sites/xxx/player/tmp/broccoli_merge_trees-output_path-LSftJmM8.tmp/assets/vendor/phoenix.js:953:1)\n    at new LongPoll (/Users/oskar/Sites/xxx/player/tmp/broccoli_merge_trees-output_path-LSftJmM8.tmp/assets/vendor/phoenix.js:919:1)\n    at Socket.connect (/Users/oskar/Sites/xxx/player/tmp/broccoli_merge_trees-output_path-LSftJmM8.tmp/assets/vendor/phoenix.js:697:1)\n    at Class.connect (/Users/oskar/Sites/xxx/player/tmp/broccoli_merge_trees-output_path-LSftJmM8.tmp/assets/addon-tree-output/phoenix/s
```

**Comment by oskarrough** [comment]
Also related to fix fastboot support: https://github.com/mike-north/ember-phoenix/pull/80
